gsb_visiteur_connexion:
    path:     /
    defaults: { _controller: GSBVisiteurBundle:Connexion:connecter }
    
gsb_visiteur_deconnexion:
    path:     /logout
    defaults: { _controller: GSBVisiteurBundle:Connexion:deconnecter }
    
gsb_visiteur_accueil:
    path:     /accueil
    defaults: { _controller: GSBVisiteurBundle:Connexion:accueil }

gsb_visiteur_ajouter:
    path:     /visiteur/ajouter
    defaults: { _controller: GSBVisiteurBundle:Formulaire:form }
  
gsb_visiteur_etat:
    path:     /etat/ajouter
    defaults: { _controller: GSBVisiteurBundle:Etat:etat }
    
gsb_visiteur_fraisforfait:
    path:     /fraisforfait/ajouter
    defaults: { _controller: GSBVisiteurBundle:FraisForfait:fraisforfait }

gsb_visiteur_consulter:
    path:     /fichefrais/consulter
    defaults: { _controller: GSBVisiteurBundle:FicheFrais:listerFicheFrais }
    
gsb_visiteur_fichefrais:
    path:     /fichefrais/ajouter
    defaults: { _controller: GSBVisiteurBundle:FicheFrais:fichefrais }

gsb_visiteur_fichefrais_modif:
    path:     /fichefrais/modifier/{id}
    defaults: { _controller: GSBVisiteurBundle:FicheFrais:fichefraisModif }

gsb_visiteur_lignefraisforfait_modif:
    path:     /fichefrais/LigneFF/modifier/{id}
    defaults: { _controller: GSBVisiteurBundle:LigneFraisForfait:lignefraisforfaitModif }

gsb_visiteur_lignefraishorsforfait_modif:
    path:     /fichefrais/LigneFHF/modifier/{id}
    defaults: { _controller: GSBVisiteurBundle:LigneFraisHorsForfait:lignefraishorsforfaitModif }

gsb_visiteur_lignefraishorsforfait_supprimer:
    path:     /fichefrais/LigneFHF/supprimer/{id}
    defaults: { _controller: GSBVisiteurBundle:LigneFraisHorsForfait:deleteFraisHorsForfait }

gsb_visiteur_listerfichefrais:
    path:     /fichefrais/consulter/{id}
    defaults: { _controller: GSBVisiteurBundle:FicheFrais:listerFicheFrais}

gsb_visiteur_listeLigneFraisForfait:
    path: /fichefrais/consulter/LigneFF/{fichefrais}
    defaults: { _controller: GSBVisiteurBundle:LigneFraisForfait:listeLigneFraisForfait } 

gsb_visiteur_listeLigneFraisHorsForfait:
    path: /fichefrais/consulter/LigneFHF/{fichefrais}
    defaults: { _controller: GSBVisiteurBundle:LigneFraisHorsForfait:listerFraisHorsForfait } 
    
gsb_visiteur_lignefraisforfait:
    path:     /lignefraisforfait/ajouter
    defaults: { _controller: GSBVisiteurBundle:LigneFraisForfait:lignefraisforfait }
    
gsb_visiteur_lignefraishorsforfait:
    path:     /lignefraishorsforfait/ajouter
    defaults: { _controller: GSBVisiteurBundle:LigneFraisHorsForfait:lignefraishorsforfait }