<?php

namespace GSB\VisiteurBundle\Repository;
use Doctrine\ORM\EntityRepository; 
use Doctrine\ORM\Query\Expr\Join;
/**
 * FicheFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheFraisRepository extends \Doctrine\ORM\EntityRepository
{
 public function listerFicheFrais($visiteur)
    {
    $qb = $this->_em->createQueryBuilder();
    $qb->select('v')
    ->from('GSBVisiteurBundle:FicheFrais', 'v')
    ->where ($qb->expr()->eq('v.visiteur',':val'))
    ->setParameter('val',$visiteur);
    $query = $qb->getQuery();
    $resultat = $query->getResult();
    return $resultat;

    }
 public function idFicheFrais($id)
    {
    $qb = $this->_em->createQueryBuilder();
    $qb->select('f')
    ->from('GSBVisiteurBundle:FicheFrais', 'f')
    ->where ($qb->expr()->eq('f.id',':val'))
    ->setParameter('val',$id);
    $query = $qb->getQuery();
    
    return $query;

    }
public function dateFicheFrais($date)
    {
    $qb = $this->_em->createQueryBuilder();
    $qb->select('f')
    ->from('GSBVisiteurBundle:FicheFrais', 'f')
    ->where ($qb->expr()->eq('f.mois',':val'))
    ->setParameter('val',$date);
    $query = $qb->getQuery()->getResult();
    
    return $query;

    }
}
