<?php

namespace GSB\VisiteurBundle\Repository;

/**
 * LigneFraisForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneFraisForfaitRepository extends \Doctrine\ORM\EntityRepository
{
function listerLigneFraisForfait($fichefrais)
    {
    $qb = $this->_em->createQueryBuilder();
    $qb->select('v')
    ->from('GSBVisiteurBundle:LigneFraisForfait', 'v')
    ->where ($qb->expr()->eq('v.fichefrais',':val'))
    ->setParameter('val',$fichefrais);
    $query = $qb->getQuery();
    $resultat = $query->getResult();
    return $resultat;
    }
}
